name: CI Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install pytest streamlit 

      - name: List files and check test file
        run: |
          ls -la
          echo "Content of _test.py:"
          head -5 _test.py
          echo "Checking Python syntax:"
          python -m py_compile _test.py

      - name: Run tests
        run: |
          echo "Running pytest with discovery"
          python -m pytest _test.py -v --tb=short
          
      - name: Verify app can be imported
        run: |
          python -c "import app; print('App imported successfully')" 



    